#
# embedXcode
# ----------------------------------
# Embedded Computing on Xcode
#
# Copyright © Rei VILO, 2010-2016
# http://embedxcode.weebly.com
# All rights reserved
#
# Last update: Jun 23, 2016 release 4.5.6
#

# ----------------------------------
# DO NOT EDIT THIS FILE.
# ----------------------------------

EMBEDXCODE_RELEASE      = 4.5.6
EMBEDXCODE_DATE         = Jun 23, 2016
EMBEDXCODE_MESSAGE      = Dedicated folder embedXcode4 

# ~
EMBEDXCODE_EDITION      = embedXcode for Wiring / Arduino
EMBEDXCODE_REFERENCE    = embedXcode
EMBEDXCODE_TEMPLATE     = ePsiEJEtRXnDNaFGpywBX9vzeNQP4vUb
# ~~


# mbed SDK
# ----------------------------------
# BLE requires 92, otherwise 112
#
MBED_SDK_RELEASE        = 92


# Arduino.ORG
# ----------------------------------
#
ARDUINO_ORG_RELEASE     = 1.7.10


# Arduino.CC or Genuino with Boards Manager
# ----------------------------------
#
ARDUINO_CC_RELEASE      = 1.6.9

ARDUINO_AVR_RELEASE     = 1.6.11
AVR_GCC_RELEASE         = 4.8.1-arduino5
AVRDUDE_RELEASE         = 6.0.1-arduino5

# Boards for Arduino.CC 1.6.5 or Genuino
#
ADAFRUIT_AVR_RELEASE    = 1.4.7
ADAFRUIT_SAMD_RELEASE   = 1.0.9

ARDUCAM_ESP_RELEASE     = 2.1.0
ARDUCAM_ESP_TOOLS_RELEASE       = 0.4.8
ARDUCAM_ESP_MKSPIFFS_RELEASE    = 0.1.2
ARDUCAM_ESP_EXTENSA_RELEASE     = 1.20.0-26-gb404fb9-2

ARDUINO_SAM_RELEASE     = 1.6.8
ARDUINO_SAMD_RELEASE    = 1.6.6
ARM_GCC_RELEASE         = 4.8.3-2014q1
BOSSAC_RELEASE          = 1.6.1-arduino
CMSIS_RELEASE           = 4.0.0-atmel
OPENOCD_RELEASE         = 0.9.0-arduino

CHIPKIT_RELEASE         = 1.1.0
PIC32_GCC_RELEASE       = 4.8.3-pic32gcc
PIC32_PROG_RELEASE      = v1.0.01-pic32gcc

COSA_AVR_RELEASE        = 1.2.0

DIGISTUMP_AVR_RELEASE   = 1.6.7
DIGISTUMP_OAK_RELEASE   = 1.0.1
DIGISTUMP_SAM_RELEASE   = 1.6.5
DIGISTUMP_OAK_ESPTOOLS_RELEASE    = 0.9.1
DIGISTUMP_OAK_MKSPIFFS_RELEASE    = 0.1.2
DIGISTUMP_OAK_OAKCLI_RELEASE      = 1.0.1
DIGISTUMP_OAK_EXTENSA_RELEASE     = 1.20.0-26-gb404fb9-2

ESP8266_RELEASE         = 2.2.0
ESPTOOLS_RELEASE        = 0.4.8
EXTENSA_RELEASE         = 1.20.0-26-gb404fb9-2

INTEL_EDISON_RELEASE    = 1.6.7+1.0
INTEL_GALILEO_RELEASE   = 1.6.7+1.0
INTEL_CURIE_RELEASE     = 1.0.5
INTEL_ARC_RELEASE       = 1.6.4+1.0
INTEL_CORE2_RELEASE     = 1.6.2+1.0
INTEL_I586_RELEASE      = 1.6.2+1.0
INTEL_UPLOAD_RELEASE    = 1.6.2+1.0
INTEL_CURIE_UPLOAD_RELEASE = 1.6.4+1.18

LINKIT_ONE_RELEASE      = 1.1.23
LINKIT_DUO_RELEASE      = 0.1.8

LITTLEROBOTFRIENDS_AVR_RELEASE = 1.6.0

MOTEINO_AVR_RELEASE     = 1.1.0

PANSTAMP_AVR_RELEASE    = 1.5.4
PANSTAMP_MSP_RELEASE    = 1.0.6

REDBEARLAB_DUO_RELEASE  = 0.2.7
DUO_GCC_ARM_RELEASE     = 4.9-2015-q3
REDBEARLAB_AVR_RELEASE  = 1.0.2
REDBEARLAB_NRF_RELEASE  = 1.0.5
NRF_GCC_ARM_RELEASE     = 4.8.3-2014q1

RFDUINO_RELEASE         = 2.3.1
SIMBLEE_RELEASE         = 1.0.3

UDOO_NEO_RELEASE        = 1.6.5-00016-g821a875
UDOO_GCC_ARM_RELEASE    = 4.9-2014q4-20141203
UDOO_CLIENT_RELEASE     = 1.0
